version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    command:
      # DASHBOARD
      - --api
      - --api.insecure=true
      
      # ENTRYPOINT
      - --entrypoints.http.address=:80
      # - --entrypoints.https.address=:443

      # PROVIDERS
      - --providers.docker

      # LOGGING
      #? Access logs.
      - --accesslog=true
      - --accesslog.bufferingsize=100
      - --accesslog.filepath=/traefik/access.log
      - --accesslog.format=json
      #? Error logs.
      - --log=true
      - --log.level=DEBUG
      - --log.filepath=/traefik/error.log
      - --log.format=json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/traefik
    labels:
    # ROUTER
    # [dashboard] 8080: Traefik API/Dashboard
      traefik.http.routers.dashboard.rule: Host(`${TRAEFIK_8080_DOMAIN?TRAEFIK_8080_DOMAIN not set}`)

      traefik.http.routers.dashboard.service: api@internal
    ports:
      - "80:80"

  whoami:
    image: jwilder/whoami
    labels: # auto-detects port 8000 in next line
      traefik.http.routers.whoami.rule: Host(`${WHOAMI_8000_DOMAIN?WHOAMI_8000_DOMAIN not set}`)