version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    command:
      #! ENTRYPOINT
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      #! PROVIDERS
      - --providers.docker
      - --providers.docker.exposedbydefault=false

      #! SSL/TLS Let's Encrypt
      #? [letsencrypt] Production CA.
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${SSL_EMAIL?SSL_EMAIL not set}

      #! LOGGING
      #? Access logs.
      - --accesslog=true
      - --accesslog.bufferingsize=100
      - --accesslog.filepath=/traefik/access.log
      - --accesslog.format=json
      #? Error logs.
      - --log=true
      - --log.level=DEBUG
      - --log.filepath=/traefik/error.log
      - --log.format=json

      #! DASHBOARD
      - --api
      - --api.dashboard=true
      - --api.insecure=true # only remove if PRODUCTION SSL is used.
    labels:
      #! NETWORK
      traefik.enable: true
      traefik.docker.network: traefik-public

      #! ROUTER: [dashboard] 8080: Traefik API/Dashboard
      traefik.http.services.traefik-dashboard.loadbalancer.server.port: 8080
      #? HTTP
      traefik.http.routers.traefik-dashboard-http.entrypoints: http
      traefik.http.routers.traefik-dashboard-http.rule: Host(`${TRAEFIK_8080_DOMAIN?TRAEFIK_8080_DOMAIN not set}`)
      #? HTTPS
      traefik.http.routers.traefik-dashboard-https.entrypoints: https
      traefik.http.routers.traefik-dashboard-https.rule: Host(`${TRAEFIK_8080_DOMAIN?TRAEFIK_8080_DOMAIN not set}`)
      #? SSL/TLS
      traefik.http.routers.traefik-dashboard-https.tls: true
      traefik.http.routers.traefik-dashboard-https.tls.certresolver: letsencrypt

      #! MIDDLEWARE
      #? [dashboard] Redirect HTTP to HTTPS.
      traefik.http.routers.traefik-dashboard-http.middlewares: https-redirect
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
      #? [dashboard] Basic Auth.
      traefik.http.routers.traefik-dashboard-https.middlewares: basic-auth
      traefik.http.middlewares.basic-auth.basicauth.users: ${TRAEFIK_8080_AUTH?TRAEFIK_8080_AUTH not set}

      #! EXTRAS
      #? Use the special Traefik service api@internal for the UI/Dashboard
      traefik.http.routers.traefik-dashboard.service: api@internal
    networks:
      - traefik-public
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/traefik
    ports:
      - "80:80"
      - "443:443"

networks:
  traefik-public:
    external: true